"""
autofill.py
Builds a consolidated, downloadable text summary of the student's common
details plus their ranked scheme list -- so they can copy values once
instead of re-typing them on every external application form.
"""


def generate_summary_text(student, ranked_results):
    lines = []
    lines.append("=" * 60)
    lines.append("SCHOLARSHIP APPLICATION SUMMARY SHEET")
    lines.append("=" * 60)
    lines.append("")
    lines.append("COMMON DETAILS (reuse these across every application form)")
    lines.append("-" * 60)
    lines.append(f"Name           : {student.get('name', '')}")
    lines.append(f"Annual Income  : Rs. {student['income']:,.0f}")
    lines.append(f"Category       : {student['category']}")
    if student.get("tenth_pct") not in (None, ""):
        lines.append(f"10th Marks (%) : {student['tenth_pct']}")
    lines.append(f"12th Marks (%) : {student['twelfth_pct']}")
    lines.append(f"State          : {student['state']}")
    lines.append(f"Course         : {student['course']}")
    lines.append(f"Gender         : {student.get('gender', '')}")
    lines.append("")
    lines.append(f"RECOMMENDED SCHOLARSHIPS ({len(ranked_results)} eligible, ranked by fit)")
    lines.append("-" * 60)
    for item in ranked_results:
        s = item["scheme"]
        lines.append(f"{item['rank']}. {s['scheme_name']}  (Match score: {item['match_score']})")
        lines.append(f"   Provider        : {s['provider']}")
        lines.append(f"   Deadline        : {s['deadline']}")
        lines.append(f"   Documents needed: {s['documents_required']}")
        lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by AI-Based Scholarship Eligibility Matching System")
    return "\n".join(lines)
